### ISSUE TITLE
Make faucet work with new tx format

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr-faucet#11]
Bump js-chain-libs and fix APIs for faucet. Releated to https://github.com/input-output-hk/jormungandr-ops/issues/24

**Comment by manveru** [comment]
Replaced with new faucet implementation in https://github.com/input-output-hk/jormungandr-faucet/commit/473dabaf8fb88d43fa6c768d09e3e17f4e02c6ae
